// TUNING — the scripted baselines' parameters were SEARCHED, not guessed.
//
// This re-runs the same deterministic grid sweep that produced the committed table
// (`docs/baseline-sweep.md`, generated by `scripts/sweep-baselines.ts`) and asserts
// the shipped constants are still what the harness selects. Change `maxClaims` or
// `minYield` without re-running the sweep and this fails; change the engine so the
// old choice stops winning and this fails too — which is the point. It is slow
// (~4 min of pure engine) because the objective is the real one: full 18-turn
// nine-seat episodes of the certification mix.
import { describe, expect, it } from "vitest";

import {
  CLAIM_GRID,
  MIN_YIELD_GRID,
  SWEEP_SEEDS,
  TOLERANCE,
  bestRow,
  playEpisode,
  selectRow,
  sweepHomesteader,
  sweepRaider,
} from "./tune";
import { HOMESTEADER_PARAMS, RAIDER_PARAMS } from "./scripted";
import { MAX_ORDERS_PER_TURN } from "../shared/engine/constants";

const TIMEOUT = 600_000;

describe("the baseline grid harness", () => {
  it("selects the SHIPPED homesteader parameters out of the whole grid", () => {
    const rows = sweepHomesteader();
    expect(rows).toHaveLength(CLAIM_GRID.length);
    const chosen = selectRow(rows);
    expect(chosen.params).toEqual(HOMESTEADER_PARAMS);
    expect(chosen.shipped).toBe(true);
    // Inside the band by construction, and strictly better than every SMALLER
    // candidate — a claim cap below the shipped one is a real loss, not a tie.
    const best = bestRow(rows);
    expect(chosen.score).toBeGreaterThanOrEqual(best.score * (1 - TOLERANCE));
    for (const row of rows) {
      if (row.params.maxClaims < chosen.params.maxClaims) expect(row.score).toBeLessThan(chosen.score);
    }
  }, TIMEOUT);

  it("selects the SHIPPED raider parameters out of the whole grid", () => {
    const rows = sweepRaider();
    expect(rows).toHaveLength(CLAIM_GRID.length * MIN_YIELD_GRID.length);
    const chosen = selectRow(rows);
    expect(chosen.params).toEqual(RAIDER_PARAMS);
    expect(chosen.shipped).toBe(true);
    const best = bestRow(rows);
    expect(chosen.score).toBeGreaterThanOrEqual(best.score * (1 - TOLERANCE));
    // No candidate with fewer claims is inside the band.
    for (const row of rows) {
      if (row.params.maxClaims < chosen.params.maxClaims) {
        expect(row.score).toBeLessThan(best.score * (1 - TOLERANCE));
      }
    }
  }, TIMEOUT);

  it("is deterministic: the same seed and parameters give the identical scores", () => {
    const a = playEpisode(SWEEP_SEEDS[0]!, HOMESTEADER_PARAMS, RAIDER_PARAMS);
    const b = playEpisode(SWEEP_SEEDS[0]!, HOMESTEADER_PARAMS, RAIDER_PARAMS);
    expect(a).toEqual(b);
    expect(a).toHaveLength(9);
    expect(a.reduce((x, y) => x + y, 0)).toBeGreaterThan(0);
  }, TIMEOUT);

  it("keeps both tuned policies inside the order cap", () => {
    // A raider spends one order on the raze, so the tuned claim cap must leave
    // room for it under MAX_ORDERS_PER_TURN.
    expect(RAIDER_PARAMS.maxClaims + 1).toBeLessThanOrEqual(MAX_ORDERS_PER_TURN);
    expect(HOMESTEADER_PARAMS.maxClaims).toBeLessThanOrEqual(MAX_ORDERS_PER_TURN);
  });
});
