#!/usr/bin/env python3
"""Post-process the nano-banana raws into clean Territory game icons.

Source raws live in `scripts/art/source/<name>.png` (committed; generated by
`scripts/art/gen_territory_art.py`). For each: trim any uniform near-white frame
the generator sometimes adds, pad to a centered square on pure black, and emit

  - src/client/icons/<name>.png              256px, black bg (drops onto the dark UI)
  - src/client/icons/transparent/<name>.png  256px, RGBA (black keyed to alpha)

plus the TERRITORY wordmark (background-knocked and autocropped) as
`src/client/art/logo-wordmark.png`, the favicon / apple-touch-icon from the logo
raw, and a labeled contact sheet.

The icons live under src/ (not public/) because the client IMPORTS them through
vite, which inlines each PNG as a data URI — path-served art 404s under the
static-replay-bundle prefix, but a data URI renders everywhere.

The SRC map below pins each `<name>` to its raw filename; update it when
regenerating.

    python3 scripts/process-icons.py
"""
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parent.parent
RAW = ROOT / "scripts" / "art" / "source"
OUT = ROOT / "src" / "client" / "icons"
OUT_T = OUT / "transparent"
ART = ROOT / "src" / "client" / "art"
for d in (OUT, OUT_T, ART, ROOT / "public"):
    d.mkdir(parents=True, exist_ok=True)

# name -> raw filename, in display order.
SRC = {
    "wall": "wall.png",
    "wall-rich": "wall-rich.png",
    "cracked": "cracked.png",
    "rubble": "rubble.png",
    "paint-splatter": "paint-splatter.png",
    "hearth": "hearth.png",
    "skull": "skull.png",
    "logo": "logo.png",
}
WORDMARK = "wordmark.png"
LABELS = {
    "wall": "Wall",
    "wall-rich": "Rich wall",
    "cracked": "Cracked",
    "rubble": "Rubble",
    "paint-splatter": "Paint",
    "hearth": "Hearth",
    "skull": "Eliminated",
    "logo": "Logo",
}
SIZE = 256


def trim_white_border(img: Image.Image) -> Image.Image:
    """Crop away any fully near-white frame rows/cols around the edges."""
    a = np.asarray(img)
    h, w, _ = a.shape
    white = a.min(axis=2) > 235
    top, bottom, left, right = 0, h - 1, 0, w - 1
    while top < bottom and white[top].all():
        top += 1
    while bottom > top and white[bottom].all():
        bottom -= 1
    while left < right and white[:, left].all():
        left += 1
    while right > left and white[:, right].all():
        right -= 1
    return img.crop((left, top, right + 1, bottom + 1))


def pad_square(img: Image.Image) -> Image.Image:
    w, h = img.size
    s = max(w, h)
    canvas = Image.new("RGB", (s, s), (0, 0, 0))
    canvas.paste(img, ((s - w) // 2, (s - h) // 2))
    return canvas


def to_transparent(rgb: Image.Image) -> Image.Image:
    """Key the near-black background to alpha via brightness; the glow stays
    opaque and glass bodies stay present (not see-through) so the icons read well
    at small HUD sizes."""
    a = np.asarray(rgb).astype(np.float32)
    alpha = np.clip(a.max(axis=2) * 2.1, 0, 255).astype(np.uint8)
    boosted = np.clip(a * 1.08, 0, 255).astype(np.uint8)
    return Image.fromarray(np.dstack([boosted, alpha]))


def autocrop_dark(rgba: Image.Image, threshold: int = 90) -> Image.Image:
    """Crop to the luminous content, dropping the dead charcoal margin. Used for
    the wordmark, where a square pad would waste most of the header height."""
    a = np.asarray(rgba)
    lit = a[:, :, 3] > threshold
    rows = np.where(lit.any(axis=1))[0]
    cols = np.where(lit.any(axis=0))[0]
    if rows.size == 0 or cols.size == 0:
        return rgba
    pad = 6
    top = max(0, int(rows[0]) - pad)
    bottom = min(a.shape[0], int(rows[-1]) + 1 + pad)
    left = max(0, int(cols[0]) - pad)
    right = min(a.shape[1], int(cols[-1]) + 1 + pad)
    return rgba.crop((left, top, right, bottom))


clean: dict[str, Image.Image] = {}
for name, fname in SRC.items():
    raw = Image.open(RAW / fname).convert("RGB")
    sq = pad_square(trim_white_border(raw)).resize((SIZE, SIZE), Image.LANCZOS)
    sq.save(OUT / f"{name}.png")
    to_transparent(sq).save(OUT_T / f"{name}.png")
    clean[name] = sq
    print(f"  {name:15s} <- {fname}")

# The wordmark: background-knock, then autocrop to the glyphs (no square pad).
mark_raw = Image.open(RAW / WORDMARK).convert("RGB")
mark = autocrop_dark(to_transparent(trim_white_border(mark_raw)))
scale = 96 / mark.height
mark = mark.resize((max(1, round(mark.width * scale)), 96), Image.LANCZOS)
mark.save(ART / "logo-wordmark.png")
print(f"  wordmark        <- {WORDMARK}  ({mark.width}x{mark.height})")

# Favicon + apple-touch from the logo.
logo_rgb = clean["logo"]
to_transparent(logo_rgb).resize((64, 64), Image.LANCZOS).save(ROOT / "public" / "favicon.png")
logo_rgb.resize((180, 180), Image.LANCZOS).save(ROOT / "public" / "apple-touch-icon.png")
print("  favicon.png + apple-touch-icon.png <- logo")

# Labeled contact sheet for preview.
cols, cell, pad, label_h = 4, 256, 24, 34
rows = (len(SRC) + cols - 1) // cols
W = cols * cell + (cols + 1) * pad
H = rows * (cell + label_h) + (rows + 1) * pad
sheet = Image.new("RGB", (W, H), (7, 7, 12))
draw = ImageDraw.Draw(sheet)
try:
    font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 22)
except OSError:
    font = ImageFont.load_default()
for i, name in enumerate(SRC):
    r, c = divmod(i, cols)
    x = pad + c * (cell + pad)
    y = pad + r * (cell + label_h + pad)
    sheet.paste(clean[name], (x, y))
    txt = LABELS[name]
    tw = draw.textlength(txt, font=font)
    draw.text((x + (cell - tw) / 2, y + cell + 6), txt, fill=(200, 200, 215), font=font)
sheet.save(OUT / "_contact-sheet.png")
print(f"  contact sheet {W}x{H}")
print("done.")
