// Print the baseline parameter sweep as the markdown table committed at
// `docs/baseline-sweep.md`:
//
//   pnpm exec tsx scripts/sweep-baselines.ts > docs/baseline-sweep.md
//
// The same sweep runs in CI (`src/game/tune.test.ts`), which fails if the shipped
// constants stop being what the harness selects — so this table cannot drift from
// the code silently.
import {
  CLAIM_GRID,
  MIN_YIELD_GRID,
  SWEEP_SEEDS,
  SWEEP_META,
  REFERENCE_HOMESTEADER,
  REFERENCE_RAIDER,
  TOLERANCE,
  bestRow,
  selectRow,
  sweepHomesteader,
  sweepRaider,
  type SweepRow,
} from "../src/game/tune.js";
import { HOMESTEADER_PARAMS, RAIDER_PARAMS } from "../src/game/scripted.js";

function table(rows: SweepRow[]): string {
  const best = bestRow(rows);
  const chosen = selectRow(rows);
  const lines = ["| parameters | mean banked | vs best | selected |", "|---|---|---|---|"];
  for (const row of rows) {
    const delta = `${(((row.score - best.score) / best.score) * 100).toFixed(1)} %`;
    const marks = [row.label === chosen.label ? "**selected**" : "", row.shipped ? "shipped" : "", row.label === best.label ? "argmax" : ""];
    const mark = marks.filter((m) => m !== "").join(" · ");
    lines.push(`| \`${row.label}\` | ${row.score.toFixed(2)} | ${delta} | ${mark} |`);
  }
  return lines.join("\n");
}

const h = sweepHomesteader();
const r = sweepRaider();

process.stdout.write(`<!-- GENERATED by scripts/sweep-baselines.ts — do not hand-edit. -->
# Scripted-baseline parameter sweep

The two scripted baselines have three free numbers between them
(\`homesteader.maxClaims\`, \`raider.maxClaims\`, \`raider.minYield\`). They were
**searched, not guessed**: this table is a deterministic grid sweep over
${SWEEP_META.seeds.length} seeded ${SWEEP_META.turns}-turn ${SWEEP_META.seats}-seat episodes of the
certification mix (five homesteaders, four raiders), run by
\`src/game/tune.ts\` and re-run in CI by \`src/game/tune.test.ts\`.

* **Objective** — the mean banked score (\`Σ income + Σ salvage\`, the number the
  league ranks by) of the seats playing the candidate, averaged over the seeds.
  The other baseline is held at the REFERENCE field
  (\`homesteader ${JSON.stringify(REFERENCE_HOMESTEADER)}\`,
  \`raider ${JSON.stringify(REFERENCE_RAIDER)}\` — the pre-tuning numbers), so every row
  of every table is comparable and tuning one policy cannot move the other's table.
* **Seeds** — \`${JSON.stringify(SWEEP_SEEDS)}\`; **grid** — \`maxClaims ∈ ${JSON.stringify(CLAIM_GRID)}\`,
  \`minYield ∈ ${JSON.stringify(MIN_YIELD_GRID)}\`.
* **Selection rule** — the SMALLEST parameters whose mean is within
  ${(TOLERANCE * 100).toFixed(0)} % of the grid's best. Parsimony is the tie-break because these are
  certification/filler policies: a smaller order set is cheaper on the wire and in
  the prompt, and the design note's baseline contract is a short order list. Above
  \`maxClaims = 3\` the curve is flat (the extra claims are rarely affordable), so
  the band is where the real answer lives, not the raw argmax.

Shipped: \`homesteader ${JSON.stringify(HOMESTEADER_PARAMS)}\`, \`raider ${JSON.stringify(RAIDER_PARAMS)}\`.

## homesteader (raiders held at the reference field, scored on seats 0-4)

${table(h)}

## raider (homesteaders held at the reference field, scored on seats 5-8)

${table(r)}
`);
